name: rituals
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.12.2


dependencies:
  flutter:
    sdk: flutter

  
  cupertino_icons: ^1.0.8

  flutter_slidable: ^4.0.3
  isar_community: ^3.3.2
  isar_community_flutter_libs: ^3.3.2
  path_provider: ^2.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  isar_community_generator: ^3.3.2
  build_runner: ^2.4.0

  
  flutter_lints: ^6.0.0


flutter:

  
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  
  fonts:
    - family: Fraunces
      fonts:
        - asset: assets/fonts/fraunces/Fraunces-Regular.ttf
          weight: 400
        - asset: assets/fonts/fraunces/Fraunces-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/fraunces/Fraunces-Bold.ttf
          weight: 700
        - asset: assets/fonts/fraunces/Fraunces-Black.ttf
          weight: 900

    - family: Manrope
      fonts:
        - asset: assets/fonts/manrope/Manrope-Regular.ttf
          weight: 400
        - asset: assets/fonts/manrope/Manrope-Medium.ttf
          weight: 500
        - asset: assets/fonts/manrope/Manrope-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/manrope/Manrope-Bold.ttf
          weight: 700
  
  
